<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE TVSCHEDULE[

<!ELEMENT Books (book+)>

<!ELEMENT book (title?, isbn+, (zipcode | author), publish*)>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
    name CDATA #IMPLIED>

<!ELEMENT isbn (#PCDATA)>
<!ATTLIST isbn
    no CDATA #REQUIRED>

<!ELEMENT zipcode (#PCDATA)>
<!ATTLIST zipcode
    Zname CDATA "232232323">

<!ELEMENT author (#PCDATA)>

<!ELEMENT publish (#PCDATA)>
<!ATTLIST publish
    year CDATA "1995">
]>

<Books>
    <book>
        <title name="Book Title">Never Hurts</title>
        <isbn no="1234567890">8848</isbn>
        <isbn no="9876543210">8848</isbn>
        <zipcode>Zcode1</zipcode>
        <publish year="1995">USA</publish>
        <publish year="1995">USA</publish>
    </book>
    <book>
        <isbn no="5432109876">8890</isbn>
        <author>Goggins</author>
    </book>
</Books>
